spring.datasource.url=jdbc:postgresql://${DB_IP:monitoring-db}:${DB_PORT:5432}/${DB_DBNAME:monitoring_db}
spring.datasource.username=${DB_USER:iulia}
spring.datasource.password=${DB_PASSWORD:iulia}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
server.port=8080
logging.level.org.springframework.amqp=DEBUG
logging.level.com.example.monitoring=DEBUG
