spring.application.name=demo


###############################################
### DATABASE CONNECTIVITY CONFIGURATIONS ###
###############################################
database.ip = ${DB_IP:localhost}
database.port = ${DB_PORT:5432}
database.user = ${DB_USER:iulia}
database.password = ${DB_PASSWORD:iulia}
database.name = ${DB_DBNAME:testdb}

spring.sql.init.platform=postgres
spring.datasource.url = jdbc:postgresql://${database.ip}:${database.port}/${database.name}
spring.datasource.username = ${database.user}
spring.datasource.password = ${database.password}

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = create
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.show_sql=true
server.tomcat.threads.max = 1
###############################################
### LOGGING CONFIGURATIONS ###
###############################################
logging.level.root=warn
logging.level.org.springframework=warn
logging.level.ro.tuc=warn
###############################################
### EMBEDDED TOMCAT CONFIGURATIONS ###
###############################################
server.address=0.0.0.0
server.port=${PORT:8080}

# External services
device.service.base-url=${DEVICE_SERVICE_BASE_URL:http://localhost:8080}
auth.service.base-url=${AUTH_SERVICE_BASE_URL:http://auth-service:8080}

###############################################
### JWT CONFIGURATION ###
###############################################
jwt.secret=${JWT_SECRET:iuliaiuliaiuliaiuliaiuliaiulia01112003}
jwt.expiration=86400000
jwt.header=Authorization
jwt.prefix=Bearer

###############################################
### SWAGGER/OPENAPI CONFIGURATION ###
###############################################
springdoc.swagger-ui.path=/api/people/swagger-ui.html
springdoc.api-docs.path=/api/people/v3/api-docs
