###############################################
### SPRING APPLICATION ###
###############################################
spring.application.name=demo
server.port=${PORT:8080}
server.address=0.0.0.0

###############################################
### DATABASE CONNECTIVITY CONFIGURATIONS ###
###############################################
database.ip=${DB_IP:localhost}
database.port=${DB_PORT:5432}
database.user=${DB_USER:iulia}
database.password=${DB_PASSWORD:iulia}
database.name=${DB_DBNAME:auth_db}

spring.datasource.url=jdbc:postgresql://${database.ip}:${database.port}/${database.name}
spring.datasource.username=${database.user}
spring.datasource.password=${database.password}
# Explicit driver to ensure classpath lookup
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.session.jdbc.initialize-schema=always
spring.sql.init.platform=postgres

###############################################
### LOGGING CONFIGURATIONS ###
###############################################
logging.level.root=warn
logging.level.org.springframework=warn
logging.level.ro.tuc=warn
logging.level.com.DemoService=debug

###############################################
### EXTERNAL SERVICES ###
###############################################
device.service.base-url=${DEVICE_SERVICE_BASE_URL:http://localhost:8080}

###############################################
### JWT CONFIGURATION ###
###############################################
jwt.secret=${JWT_SECRET:iuliaiuliaiuliaiuliaiuliaiulia01112003}
jwt.expiration=86400000
jwt.header=Authorization
jwt.prefix=Bearer

###############################################
### SWAGGER/OPENAPI CONFIGURATION ###
###############################################
springdoc.swagger-ui.path=/api/auth/swagger-ui.html
springdoc.api-docs.path=/api/auth/v3/api-docs

###############################################
### OPTIONAL SETTINGS ###
###############################################
server.tomcat.threads.max=1
